name: basic_http_server
author: Seth Ladd <sethladd@gmail.com>
version: 0.0.1
homepage: https://github.com/igrigorik/heroku-buildpack-dart
description: A minimal static HTTP server to demonstrate Dart on Heroku.
environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  shelf: ^1.3.1
  path_provider: ^2.0.11
  shelf_static: ^1.1.1
